language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip3 install -r requirements.txt
  - pip3 install coveralls
  - pip3 install pytest-cov

services:
  - postgresql

before_script:
  - psql -c 'create database stackoverflow;' -U postgres
  - psql -c 'create database stackoverflow_tests;' -U postgres
  
# command to run tests
script:
  - python3 -m pytest --cov=app tests/

after_success:
- coveralls
